// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "cellar": js TestHelpers
//
// Command:
// $ goagen
// --design=github.com/made2591/edam/design
// --out=$(GOPATH)/src/github.com/made2591/edam
// --version=v1.3.0

package test
